on: [push]

jobs:
  build-and-run-in-bash:
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: arm64
          - os: ubuntu-latest
            arch: x64
          - os: windows-latest
            arch: x64
    runs-on: ${{ matrix.os }}
    name: Build and run in Bash
    steps:
      - uses: actions/checkout@v4
      - uses: radekm/setup-c3@122e94388b9e77cd3da534b46b7473f3f96a18b2
        with:
          version: v0.6.5
      - shell: bash
        run: c3c compile-run --lib somelib someprogram.c3
  build-and-run-in-cmd:
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: x64
    runs-on: ${{ matrix.os }}
    name: Build and run in cmd
    steps:
      - uses: actions/checkout@v4
      - uses: radekm/setup-c3@122e94388b9e77cd3da534b46b7473f3f96a18b2
        with:
          version: v0.6.5
      - shell: cmd
        run: c3c compile-run --lib somelib someprogram.c3
